/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.st0kke.rentalreview.restservices.service.config;

import java.util.HashSet;
import java.util.Set;
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

/**
 *
 * @author 
 */
@ApplicationPath("services")
public class ApplicationConfigREST extends Application {
    
    @Override
    public Set<Class<?>> getClasses() {
        
        Set<Class<?>> s = new HashSet<Class<?>>();
        addServiceClasses(s);
        return s;
    }

    private void addServiceClasses(Set<Class<?>> s) {
        s.add(com.st0kke.rentalreview.restservices.service.ReviewService.class);
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(com.st0kke.rentalreview.restservices.service.ReviewService.class);
    }
}
